### PR TITLE
Figma1.8

### PR DESCRIPTION
**Pull request by therealnikhil**
- Embedded Test and Confirm screens in ScrollView
- Updated onboarding splash screen with new logo and UI
- Updated onboarding images to v1.8

### CODE REVIEW

**Review by ibeckermayer — CHANGES_REQUESTED** [review]
Great work, the only minor issue I found was that calendar popup is awkwardly aligned over the input rectangle on the iPhone 8:
Screen Shot 2020-04-21 at 9 26 21 PM

Also went in and tinkered with some ratios etc. to get the images to work, lmk if you find any further issues.

**Comment by therealnikhil** [comment]
@ibeckermayer I played around with this for awhile to get the scrollview to work. The way I got it to work was a full size scrollview, which ignores the date picker.

**Comment by therealnikhil** [comment]
Actually hold on this gives me an idea to fix that

**Comment by therealnikhil** [comment]
Fixed

**Review by ibeckermayer — APPROVED** [review]

**Pull request merged**
