### PR TITLE
Updating Auto Layout on Splash, Bluetooth, Notifications, and Replaci…

### PR DESCRIPTION
**Pull request by jeffctown**
…ng Header on Home

- Cleaned up a lot of UI issues on the splash, bluetooth, and notifications screens.
- Converted Bluetooth and Notifications to Auto Layout
- Embedded the Splash View Controller into a Navigation Controller with its navigation bar hidden, so we get nice push animations in the onboarding flow.
- Created a new HeaderViewController using auto layout and delegates, and embedded it using a Container view into Bluetooth, Notifications, Home screens.
- Updated UI tests and added checks for the logo on Bluetooth, Notifications, & Home screens (fixing UITest todos and sonar smells)
- Moved test coverage processing from jacoco to a script provided by sonar.  I didn't expect to make this change, but my test coverage was failing in this PR for some reason. 

## Bluetooth

Screen Shot 2020-04-26 at 9 11 21 AM
Screen Shot 2020-04-26 at 9 11 11 AM
Screen Shot 2020-04-26 at 9 10 54 AM

## Notifications

Screen Shot 2020-04-26 at 9 11 46 AM

Screen Shot 2020-04-26 at 9 12 11 AM
Screen Shot 2020-04-26 at 9 12 00 AM

### CODE REVIEW

**Comment by jeffctown** [comment]
Ok.  Unit test code coverage is working now, this is ready to go.

**Review by ibeckermayer — COMMENTED** [review]
Looks good, I went in and deleted `Header.swift` and `BaseViewController.swift` and added the `Menu` back in. (Please check these revisions, I pushed them to this branch).

A few things to discuss and/or change:

1. The content on each screen should be `contentMaxWidth` wide, since this is being enforced throughout the rest of the app.
2. The button should have a height of `58 * figmaToiOSVerticalScalingFactor`, so that it scales proportionally to different screen sizes

**Comment by madhavajay** [comment]
Changes look great. Couple of small issues:

- The Hamburger menu isn't working for me
- The Covid Watch icon top left goes back to the start of onboarding?

Also I think before there was a flag which was set after hitting the first onboarding screen so that if you reject bluetooth permissions and then turn them back on and come back to the app it skips the first onboard button screen because the app is forced to reboot when you change BT permissions in the settings screen.

**Comment by jeffctown** [comment]
Oooh, thanks for catching that @ibeckermayer - and for adding the menu back in.  The shadow is looking awesome! 🔥

Onto your points:

1. iOS makes things a lot easier if we go with 20 pixels of padding on each side of the content, so I updated `contentMaxWidth` [here](https://github.com/covid19risk/covidwatch-ios/pull/111/commits/e1d897d9ea1bafd0b87bf44dc34eda78a51784e7). If you hate that idea, I can revert that and update the new layouts to be proportional.

2. Ahh, good call.  Updated those to be proportional to 58/812 of the screen height [here](https://github.com/covid19risk/covidwatch-ios/pull/111/commits/147849278a7b2a19d2e86ca5cbef13d127f4e40d).

@madhavajay - The menu should be good now. I also forgot to take the logo's image gesture recognizer out, but removed it [here](https://github.com/covid19risk/covidwatch-ios/pull/111/commits/147849278a7b2a19d2e86ca5cbef13d127f4e40d).  

On the flag you mentioned - ~~the only thing I saw like this was one called `isFirstTimeUser`.  It's not set until the Home screen, after onboarding is finished, so I done think this what you described.  I'm tempted to add another boolean to check, but there are already a lot of booleans being checked everywhere.  This feels ripe for a refactor to an enum instead of so many booleans, but I'd prefer if that be handled in a follow up.~~  I found it and fixed it. Updated [here](https://github.com/covid19risk/covidwatch-ios/pull/111/commits/121d3f32b8b41a1d410c7818475702646def0521).  I still think we should consider an enum.

**Comment by ibeckermayer** [comment]
> Oooh, thanks for catching that @ibeckermayer - and for adding the menu back in. The shadow is looking awesome! 🔥

Thanks :)

> Onto your points:
> 
> 1. iOS makes things a lot easier if we go with 20 pixels of padding on each side of the content, so I updated `contentMaxWidth` [here](https://github.com/covid19risk/covidwatch-ios/pull/111/commits/e1d897d9ea1bafd0b87bf44dc34eda78a51784e7). If you hate that idea, I can revert that and update the new layouts to be proportional.

That works, primary concern is consistency.

> 2. Ahh, good call.  Updated those to be proportional to 58/812 of the screen height [here](https://github.com/covid19risk/covidwatch-ios/pull/111/commits/147849278a7b2a19d2e86ca5cbef13d127f4e40d).

Hmm, the buttons still look short compared to the other UIButtons (on smaller screens, see the screenshots of the SE below). I think you may have linked the wrong commit, I don't see where you're pointing to. I also misled you originally -- looking at `Button.swift`, I'm setting the height proportionately to the width (`self.frame.size.height = (58.0/321.0) * contentMaxWidth`).

Screen Shot 2020-04-26 at 9 48 43 PM

VS

Screen Shot 2020-04-26 at 9 48 56 PM

Another issue this comparison revealed to me was that what used to be `MainText` and `Button.subtext`,  are no longer changing font size as the screen gets smaller (I suspect this is also true of `LargeText` and `Button.text`. Those scaling choices were primarily made in order to get all the elements to fit on the various iterations of the `Home` screen, and I argue we should keep them consistent throughout the app for the sake of integrity. Is there a way we can organize that centrally in the code, to apply to all `ALButton`s?

**Comment by jeffctown** [comment]
@ibeckermayer i think I’ve got everything addressed here. I updated the fonts and centralized them, fixed the button height, and then made the header a little shorter throughout.  Will fix the test failure before merging.

**Review by ibeckermayer — APPROVED** [review]
Great work.

**Comment by madhavajay** [comment]
Looks good and works too! :)

**Pull request merged**
