### PR TITLE
Polishing ui

### PR DESCRIPTION
**Pull request by ibeckermayer**
- Changed segues to have animated transitions
- Made Tested VC be dismissible via swipe-down
- Mimicked iOS native button animation
- Fixed Family picture wonkiness
- Added menu animation

### CODE REVIEW

**Comment by zssz** [comment]
If we go with this menu implementation and we're not using a Hamburger component from a well-tested package then the following changes need to be made:
- The menu slide animation parameters feel not right.
- Add a gesture to dismiss the menu as iOS user expect to swipe to dismiss

The layout is not right when the red banner is displayed:
IMG_0004

**Comment by ibeckermayer** [comment]
> If we go with this menu implementation and we're not using a Hamburger component from a well-tested package then the following changes need to be made:
> 
> * The menu slide animation parameters feel not right.
> * Add a gesture to dismiss the menu as iOS user expect to swipe to dismiss

This fix is ready for review

**Comment by ibeckermayer** [comment]
> The layout is not right when the red banner is displayed:
> IMG_0004

and fixed this

**Comment by madhavajay** [comment]
Looks good, only issue i can see is, during onboarding it keeps using the modal animation between screens. I guess that should only happen on the first one to bluetooth and then after that just go switch between pages left to right normally? I thought that was the old behavior?
But I think this is basically good to go since its a massive improvement on the previous version and would be great to include the new menu in the beta.

**Review by madhavajay — APPROVED** [review]

**Comment by madhavajay** [comment]
Looks good on my iPhone 11 Pro Max:
https://imgur.com/a/D0f7ksl

Have we tested the COVID Banner on iPhone SE size?

**Comment by ibeckermayer** [comment]
> Looks good on my iPhone 11 Pro Max:
> https://imgur.com/a/D0f7ksl
> 
> Have we tested the COVID Banner on iPhone SE size?

Yeah, we have logic for changing image and font sizes so that it fits on smaller screens. I've tested SE in the simulator.

**Pull request merged**
