### PR TITLE
Adding simple SonarCloud analysis into flow.

### PR DESCRIPTION
**Pull request by haydenridd**
- Also separated actions into a "pull request" and "push" flow
- Renamed for clarity
- Updated badge to match new flow name

### CODE REVIEW

**Comment by jeffctown** [comment]
Added a label so it doesn't get merged until this is ready.

**Comment by haydenridd** [comment]
Sweet looks like we're down to just SonarCloud failures! I can look into these, appreciate all the help.

**Comment by jeffctown** [comment]
Sounds good man. Anytime. 👌

**Comment by madhavajay** [comment]
Can someone figure out why the swiftlint command isnt working in CI?
https://github.com/covid19risk/covidwatch-ios/pull/104/checks?check_run_id=617416037

I changed the .swiftlint.yml so that it excludes everything and manually includes the Source code because it was failing when running against the updated TCN library. If anyone knows another way to force swiftlint to ignore the SPM packages that get included in build intermediate that would be another way. This is really annoying since an external dependency is breaking our swiftlint build and locally the SwiftLint step works flawlessly, but I think maybe the PROJECT_DIR ENV is missing in CI or something, and the error logs are not printing out my "echo"s which is making it hard to debug.

**Pull request merged**
