### PR TITLE
WIP: Feature/adding uitests to pull requests

### PR DESCRIPTION
**Pull request by jeffctown**

### CODE REVIEW

**Review by ibeckermayer — APPROVED** [review]
Thanks

**Comment by madhavajay** [comment]
Damn, i wasnt finished with this branch, but thats okay.

**Comment by madhavajay** [comment]
Final commit here:
https://github.com/covid19risk/covidwatch-ios/pull/99

**Comment by jeffctown** [comment]
I’ll make my WIP more clear next time. I wasn’t ready for this to go either. The uitests fail frequently and I was trying to figure out how bad it is.

**Pull request merged**
